# Configure this Discovery Server
eureka:
  instance:
    hostname: restcar.herokuapp.com
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8761   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
    
    
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF