spring:
  application:
    name: microservice-project
  datasource:
    url: jdbc:h2:mem:microservicedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      #path: /h2-console
      #settings:
      #  trace: false
      #  web-allow-others: false
    
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true